version: '3.8'

services:
  # Main application server - runs Express backend and serves React frontend
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tinylink
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - SUPABASE_DATABASE_URL=${SUPABASE_DATABASE_URL}
      - DB_SCHEMA=tinylink
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    command: npm start
    networks:
      - app-network

networks:
  app-network:
    name: tinylink-network
    driver: bridge