version: '3.8'

services:
  # Main application server - runs Express backend and serves React frontend
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development
    command: npm run dev
    depends_on:
      - db
      - db-init

  # PostgreSQL database  
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-tinylink}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-tinylink_password}
      - POSTGRES_DB=${POSTGRES_DB:-tinylink}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Initialize database tables and schema
  db-init:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: node create-schema.js
    env_file:
      - .env.development
    depends_on:
      - db
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

volumes:
  postgres_data: