version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-tinylink}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-tinylink_password}
      - POSTGRES_DB=${POSTGRES_DB:-tinylink}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: