version: '3.8'

services:
  # Main application server - runs Express backend and serves React frontend
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - SUPABASE_DATABASE_URL=postgres://postgres:postgres@db:5432/tinylink
      - DB_SCHEMA=tinylink
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    depends_on:
      - db
    command: npm start

  # PostgreSQL database
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tinylink
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Not exposing the database port in production for security

  # Initialize database tables and schema
  db-init:
    build:
      context: .
      dockerfile: Dockerfile
    command: node create-schema.js
    environment:
      - SUPABASE_DATABASE_URL=postgres://postgres:postgres@db:5432/tinylink
      - DB_SCHEMA=tinylink
    depends_on:
      - db
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

volumes:
  postgres_data: