// Dynamically create a runtime environment configuration for the frontend
import { Request, Response, NextFunction } from 'express';
import fs from 'fs';
import path from 'path';

// This middleware creates a runtime-config.js file that injects environment variables
// It should run before the static file middleware
export function setupRuntimeConfig(req: Request, res: Response, next: NextFunction) {
  // Only process this path
  if (req.path !== '/runtime-config.js') {
    return next();
  }
  
  // Extract the environment variables we want to expose to the client
  const config = {
    VITE_SUPABASE_URL: process.env.VITE_SUPABASE_URL || 'https://your-supabase-url.supabase.co',
    VITE_SUPABASE_ANON_KEY: process.env.VITE_SUPABASE_ANON_KEY || 'your-supabase-anon-key',
  };
  
  // Generate the JavaScript that will expose these variables
  const configScript = `
// Runtime configuration generated by the server
window.__RUNTIME_CONFIG__ = {
  VITE_SUPABASE_URL: "${config.VITE_SUPABASE_URL}",
  VITE_SUPABASE_ANON_KEY: "${config.VITE_SUPABASE_ANON_KEY}",
};
console.log('Runtime config loaded:', window.__RUNTIME_CONFIG__);
`;
  
  // Send the script with appropriate headers
  res.setHeader('Content-Type', 'application/javascript');
  res.send(configScript);
}

// This function will inject a script tag into the HTML that loads our runtime config
export function injectRuntimeConfig(html: string): string {
  const scriptTag = '<script src="/runtime-config.js"></script>';
  
  // Insert the script tag right before the closing head tag
  return html.replace('</head>', `${scriptTag}</head>`);
}